version: 2
jobs:
  style_checker:
    docker:
      - image: circleci/python
    steps:
      - checkout # Hace pull del repositorio en el directorio actual
      - run: sudo python -m pip install flake8
      - run: python -m flake8 python/ # Ejecuta flake8 con los parametros de dlint
  static_analysis:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo python -m pip install dlint
      - run: python -m flake8 --select=DUO python/ # Ejecuta flake8 con los parametros de dlint

workflows:
  version: 2
  stylecheck-build-test:
    jobs:
      - style_checker
      - static_analysis